parameters:
  - name: dev
    type: boolean
    default: false
    displayName: "Publish pre-release versions"
    
trigger:
  branches:
    include:
      - main
      - master
pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/build-steps.yaml
  - script: |
      git config --local user.email imodeljs-admin@users.noreply.github.com
      git config --local user.name imodeljs-admin
      pnpm run publish -y --message "applying package updates [skip ci]"
    displayName: "Publish packages"