parameters:
  - name: dev
    type: boolean
    default: false
    displayName: "Publish pre-release versions"
    
trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/build-steps.yaml
  # - script: pnpm unpublish @bentley/sample-a
  # - script: pnpm unpublish @bentley/sample-b
  - script: |
      git config --local user.email imodeljs-admin@users.noreply.github.com
      git config --local user.name imodeljs-admin
      pnpm run publish --message "applying package updates [skip ci]"
    displayName: "Publish packages"
  # - script: pnpm unpublish @bentley/sample-a
  # - script: pnpm unpublish @bentley/sample-b